services:
  app-server:
    build: ./server
    image: app-server:latest
    pull_policy: never
    working_dir: /app-server
    command: bash -c 'watchexec -r -c -d 2s --poll 1s -w src -w Cargo.toml -w Cargo.lock -- cargo run'
    environment:
      - LANG=C.UTF-8
      - LC_ALL=C.UTF-8
      - TZ=Asia/Tokyo
      - RUST_BACKTRACE=1
      - RUST_LOG=debug
    ports:
      - 3001:3001
    stdin_open: true
    tty: true
    volumes:
      - ./server:/app-server:cached
      - cargo-registry:/usr/local/cargo/registry
      - rust-target:/app-server/target

  app-front:
    image: node:lts-trixie-slim
    working_dir: /app-front
    command: bash -c 'corepack enable && pnpm install && pnpm exec rsbuild dev --host 0.0.0.0'
    depends_on:
      - app-server
    environment:
      - LANG=C.UTF-8
      - LC_ALL=C.UTF-8
      - TZ=Asia/Tokyo
      - COREPACK_ENABLE_DOWNLOAD_PROMPT=0
      - DOCKER_ENV=true
      - NODE_ENV=development
    ports:
      - 3000:3000
    stdin_open: true
    tty: true
    volumes:
      - ./front:/app-front:cached
      - node-modules:/app-front/node_modules
      - pnpm-store:/app-front/.pnpm-store

volumes:
  cargo-registry:
  rust-target:
  node-modules:
  pnpm-store:
