services:
  database:
    image: postgres:18-alpine
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - TZ=${TZ}
    ports:
      - 5432:5432
    healthcheck:
      test: pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB
      interval: 2s
      timeout: 5s
      retries: 3
    volumes:
      - postgres-data:/var/lib/postgresql

  app-server:
    build: ./server
    image: app-server:latest
    pull_policy: never
    working_dir: /app-server
    command: watchexec -r -c -d 2s --poll 1s -w migrations -w src -w Cargo.toml -w Cargo.lock -- cargo run
    depends_on:
      database:
        condition: service_healthy
    environment:
      - TZ=${TZ}
      - RUST_BACKTRACE=${RUST_BACKTRACE}
      - RUST_LOG=${RUST_LOG}
      - DATABASE_URL=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@database:5432/${POSTGRES_DB}
    ports:
      - 3001:3001
    stdin_open: true
    tty: true
    volumes:
      - ./server:/app-server:cached
      - cargo-registry:/usr/local/cargo/registry
      - rust-target:/app-server/target

  app-front:
    image: node:lts-trixie-slim
    working_dir: /app-front
    command: sh -c 'corepack enable && pnpm install && pnpm exec rsbuild dev --host 0.0.0.0'
    depends_on:
      - app-server
    environment:
      - TZ=${TZ}
      - COREPACK_ENABLE_DOWNLOAD_PROMPT=${COREPACK_ENABLE_DOWNLOAD_PROMPT}
      - DOCKER_ENV=${DOCKER_ENV}
      - NODE_ENV=${NODE_ENV}
    ports:
      - 3000:3000
    stdin_open: true
    tty: true
    volumes:
      - ./front:/app-front:cached
      - node-modules:/app-front/node_modules
      - pnpm-store:/app-front/.pnpm-store

volumes:
  postgres-data:
  cargo-registry:
  rust-target:
  node-modules:
  pnpm-store:
